version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-app
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    ports:
      - "6379:6379"
